# Generated by Django 5.2 on 2025-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_color', models.CharField(max_length=7)),
                ('image1', models.ImageField(upload_to='carousel_images/')),
                ('image2', models.ImageField(upload_to='carousel_images/')),
                ('image3', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
    ]
