# Generated by Django 5.2 on 2026-01-09 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g. 2025 CATALOGUE', max_length=200)),
                ('subtitle', models.CharField(help_text='E.g. FULL RANGE', max_length=200)),
                ('main_image', models.ImageField(upload_to='catalogue/main/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g. VIANA LEDGE', max_length=100)),
                ('subtitle', models.CharField(help_text='E.g. SERIES', max_length=100)),
                ('main_image', models.ImageField(upload_to='products/main/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('features', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Transform Your Space with Elegance!', max_length=200)),
                ('subtitle', models.CharField(default='Premium Cultured Stones for Interior & Exterior Excellence', max_length=300)),
                ('background_image', models.ImageField(default='slider/backgrounds/default1.jpg', upload_to='slider/backgrounds/')),
                ('shape1', models.ImageField(default='slider/shapes/triangle1.avif', upload_to='slider/shapes/')),
                ('shape2', models.ImageField(default='slider/shapes/triangle2.jpg', upload_to='slider/shapes/')),
                ('shape3', models.ImageField(default='slider/shapes/triangle3.jpg', upload_to='slider/shapes/')),
                ('shape_class', models.CharField(choices=[('shape-tri', 'Triangle'), ('shape-circ', 'Circle'), ('shape-boxy', 'Box')], default='shape-tri', help_text='Select a shape style: Triangle / Circle / Box', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/cards/')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='shop.productcatalogue')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/cards/')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='shop.productcollection')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='shop.project')),
            ],
        ),
    ]
