# Generated by Django 5.2 on 2025-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact_delete_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Transform Your Space with Elegance!', max_length=200)),
                ('subtitle', models.CharField(default='Premium Cultured Stones for Interior & Exterior Excellence', max_length=300)),
                ('background_image', models.ImageField(default='slider/backgrounds/default1.jpg', upload_to='slider/backgrounds/')),
                ('shape1', models.ImageField(default='slider/shapes/triangle1.avif', upload_to='slider/shapes/')),
                ('shape2', models.ImageField(default='slider/shapes/triangle2.jpg', upload_to='slider/shapes/')),
                ('shape3', models.ImageField(default='slider/shapes/triangle3.jpg', upload_to='slider/shapes/')),
                ('shape_class', models.CharField(default='shape-tri', help_text='Example: shape-tri / shape-circ / shape-boxy', max_length=50)),
            ],
        ),
    ]
