# Generated by Django 5.2 on 2025-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='shape_class',
            field=models.CharField(choices=[('shape-tri', 'Triangle'), ('shape-circ', 'Circle'), ('shape-boxy', 'Box')], default='shape-tri', help_text='Select a shape style: Triangle / Circle / Box', max_length=50),
        ),
    ]
