# Generated by Django 5.2 on 2025-06-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_slide_shape_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g. VIANA LEDGE', max_length=100)),
                ('subtitle', models.CharField(help_text='E.g. SERIES', max_length=100)),
                ('main_image', models.ImageField(upload_to='products/main/')),
                ('enquiry_product_name', models.CharField(help_text='For the Enquiry button', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/cards/')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='shop.productcollection')),
            ],
        ),
    ]
