# Generated by Django 5.2 on 2025-06-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcollection_productcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product_catalogue_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue_card_images/')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='shop.productcatalogue')),
            ],
        ),
    ]
