# Generated by Django 5.2 on 2025-06-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productcatalogue_cataloguecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcollection',
            name='enquiry_product_name',
        ),
    ]
