# Generated by Django 5.2 on 2025-08-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_create_admin'),
        ('shop', '0008_productenquiry'),
    ]

    operations = [
    ]
