# Generated by Django 5.2 on 2025-08-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_merge_0002_create_admin_0008_productenquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cataloguecard',
            old_name='product',
            new_name='catalogue',
        ),
        migrations.AlterField(
            model_name='cataloguecard',
            name='image',
            field=models.ImageField(upload_to='catalogue/cards/'),
        ),
        migrations.AlterField(
            model_name='productcatalogue',
            name='main_image',
            field=models.ImageField(default=0, upload_to='catalogue/main/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcatalogue',
            name='subtitle',
            field=models.CharField(help_text='E.g. FULL RANGE', max_length=200),
        ),
        migrations.AlterField(
            model_name='productcatalogue',
            name='title',
            field=models.CharField(help_text='E.g. 2025 CATALOGUE', max_length=200),
        ),
    ]
