# Generated by Django 5.2 on 2025-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_project_created_at_project_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(help_text='Enter full detailed description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(help_text='Enter up to 100 words'),
        ),
    ]
