# Generated by Django 5.2 on 2025-08-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_project_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(help_text='Enter up to 200 words'),
        ),
    ]
