# Generated by Django 5.2 on 2025-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_project_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(),
        ),
    ]
